development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: cake_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: cake_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: cake_production
  pool: 5